# Use a imagem base do Nginx
FROM nginx:latest

# Copie o arquivo HTML para o diretório de publicação do Nginx
COPY index.html /usr/share/nginx/html

# Exponha a porta 80
EXPOSE 80

# Inicie o servidor Nginx em primeiro plano
CMD ["nginx", "-g", "daemon off;"]
